### ISSUE TITLE
ID error of dragonstone

### ISSUE THREAD

**Issue by Celophy** [Sinhika/Netherrocks#13]
The id of the Dragonstone gem conflicts with that of the botania mod, and can be used in the same crafting recipes

**Comment by Sinhika** [comment]
I need some context here, because the current id of dragonstone is "netherrocks:dragonstone_gem", which cannot possibly conflict with Botania.  Are you referring to the forge tag, "#forge:gems/dragonstone"? That is intentional, it allows for cross-mod compatibility.  Are you referring to older versions of the mod?

**Comment by Celophy** [comment]
yes it is the forge tag, there is a way to disable it?

**Comment by Sinhika** [comment]
I take it there's a problem with it being cross-compatible? Dragonstone isn't exactly common as dirt. It's rarer than diamonds and in the nether.

I will consider removing the tag and rewriting the recipes that refer to it next time I update Netherrocks.

**Comment by Celophy** [comment]
ok thanks!
