### ISSUE TITLE
Illumenite Sword Effects

### ISSUE THREAD

**Issue by BioMasterZap** [Sinhika/Netherrocks#15]
When testing Netherrocks version 1.7.1.2 for 1.12, I noticed that the Illumenite Sword isn't applying the effects properly. Its tooltip notes that you get Night Vision while the target is slowed and blinded, but it seems to also apply the Blindness to the attacker rather than the target. I don't know if this was fixed in newer versions, but I didn't see it mentioned in the changelogs.

**Comment by Sinhika** [comment]
I noticed that when I was rewriting the mod for 1.15 & later, and fixed it in the newer versions. I probably neglected to mention it in the changelogs since 1.14/1.15/1.16 was a complete rewrite from 1.12. About all I kept were the textures and the specfications of how everything was supposed to behave. I am no longer maintaining 1.12, unfortunately for those still playing 1.12. Too much work to maintain and keep track of totally different code bases. If anyone else wants to maintain a 1.12 version, they are free to, the code is under an LGPL open-source license.
